apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-apps
  namespace: infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          # ── Wave 1 – Infrastructure ──────────────────────────────────
          - { name: adguard,              syncWave: "1", namespace: dns }
          - { name: cloudflared,          syncWave: "1", namespace: infra }
          - { name: media-storage,        syncWave: "1", namespace: apps }
          - { name: traefik-dashboard,    syncWave: "1", namespace: kube-system }
          # ── Wave 2 – Platform / Utilities ────────────────────────────
          - { name: homepage,             syncWave: "2", namespace: apps}
          #- { name: igotify,              syncWave: "2", namespace: apps}
          #- { name: uptime-kuma,          syncWave: "2", namespace: apps}
  template:
    metadata:
      name: "{{ .name }}"
      namespace: infra
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: default
      destination:
        namespace: '{{ .namespace }}'
        server: https://kubernetes.default.svc
      source:
        repoURL: https://gitlab.com/omerlevyk/homelab.git
        targetRevision: main
        path: 'gitops/{{ .namespace }}/{{ .name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
