apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - appset.yaml
  - app-networking.yaml
  - app-deployments.yaml
  - ../../infra/argocd
  - ../../obs/prometheus-operator-crds
  - ../../obs/kube-prometheus-stack
