apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/dns/adguard
  - ../../infra/cloudflared
  - ../../infra/argocd
  - ../../infra/traefik-dashboard
  - ../../apps/jellyfin
  - ../../apps/homepage
