apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
configMapGenerator:
  - name: cv-site
    files:
      - index.html
      - omer-levy-cv.pdf
  - name: cv-nginx
    files:
      - nginx.conf
