apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - rbac.yaml
  - deploy.yaml
  - svc.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-config
    files:
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/services.yaml
      - config/bookmarks.yaml
      - config/widgets.yaml
      - config/custom.css
