apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard.yaml
  - cloudflared.yaml
  - traefik-dashboard.yaml
  - jellyfin.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  - bazarr.yaml
  - overseerr.yaml
  - tdarr.yaml
  - gotify.yaml
  - igotify.yaml
  - uptime-kuma.yaml
  - vaultwarden.yaml
  - syncthing.yaml
  - home-assistant.yaml
  - karakeep.yaml
  - homepage.yaml
