apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: apps
spec:
  storageClassName: local-media
  volumeName: jellyfin-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
