title: Omer HomeLab
description: Infrastructure, media, and operations
theme: dark
color: slate
headerStyle: clean
hideVersion: true
statusStyle: "dot"
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
layout:
  Shortcuts:
    style: grid
    columns: 9
  Infrastructure:
    style: column
    columns: 3
  Applications:
    style: column
    columns: 3
  Networking:
    style: column
    columns: 3
  Security:
    style: column
    columns: 3
  Storage:
    style: column
    columns: 3
