title: HomeLab
description: Infrastructure, media, and operations
background: https://drive.google.com/file/d/1w6FoRsje6xkBxfSz859d7NyNRabq8DwN/view?usp=sharing
theme: dark
color: slate
headerStyle: clean
hideVersion: true
statusStyle: "dot"
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
layout:
  Shortcuts:
    style: grid
    columns: 9
  Infrastructure:
    style: column
    columns: 3
  Applications:
    style: column
    columns: 3
  Networking:
    style: column
    columns: 3
  Security:
    style: column
    columns: 3
  Storage:
    style: column
    columns: 3
