- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: k3s
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: [google, duckduckgo, brave]
    focus: true
    showSearchSuggestions: true
    target: _self

- openmeteo:
    label: Home
    latitude: 32.0853
    longitude: 34.7818
    timezone: Asia/Jerusalem
    units: metric
    cache: 10

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short

