apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: apps
spec:
  storageClassName: local-media
  volumeName: media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
