apiVersion: apps/v1
kind: Deployment
metadata:
  name: anytype
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anytype
  template:
    metadata:
      labels:
        app: anytype
        app.kubernetes.io/name: anytype
    spec:
      containers:
        - name: anytype
          image: anyproto/anytype-heart:latest
          ports:
            - containerPort: 31009
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Jerusalem
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1536Mi
