apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - emby.yaml
  - jellyfin.yaml
  - radarr.yaml
  - sonarr.yaml
  - bazarr.yaml
  - overseerr.yaml
  - home-assistant.yaml
  - home-assistant-config-bootstrap.yaml
  - qbittorrent.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - tdarr.yaml
  - karakeep.yaml
  - karakeep-secret.yaml
  - gotify.yaml
