apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-pvc
  namespace: apps
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
