apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - pvc-data.yaml
  - pvc-meilisearch.yaml
  - deploy-meilisearch.yaml
  - svc-meilisearch.yaml
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
