apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secrets
  namespace: apps
type: Opaque
stringData:
  NEXTAUTH_SECRET: Cw6QLW5DYlMnjnAdwHuOPKjQtKyFoEg/nBHe8X6EYrQ=
  OPENAI_API_KEY: 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
