name: mirror to Gitlab
on: [push]
jobs:
    mirror:
       runs-on: ubuntu-latest
       steps:
          - uses: action/checkout@v4
          - name: Push to GitLab
            run: |
               git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/omerlevyk/homelab.git
               git push --mirror gitlab
            env:
               GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
              
